#!/usr/bin/env python3
"""
Simulación 2 — Medicina Familiar / ORL y cuello (versión condensada)
Deck "Simulaciones::Familiar ORL - Repaso 2" (.apkg) + TSV de respaldo.

Uso (venv del repo):  ../../.venv/bin/python build_deck.py

Estructura por entidad (3): Abordaje (interrogatorio+exploración) + Manejo +
Caso escalonado (leve→moderado→difícil en una tarjeta). 11 entidades = 33.
"""

import genanki

MODEL_QA_ID = 1607392320  # qa_estandar del repo
DECK_ID = 2061700220      # registrado en ids.json
DECK_NAME = "Simulaciones::Familiar ORL - Repaso 2"

MODEL = genanki.Model(
    MODEL_QA_ID,
    "Estudio Medico QA",
    fields=[{"name": "Front"}, {"name": "Back"}],
    templates=[{
        "name": "QA",
        "qfmt": "{{Front}}",
        "afmt": '{{Front}}<hr id="extra">{{Back}}',
    }],
    css="""
.card { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        font-size: 19px; text-align: left; color: #1a1a1a;
        background-color: #fafafa; padding: 20px; line-height: 1.55; }
b { color: #b45309; }
i { color: #2563eb; }
ul { margin: 8px 0 8px 22px; }
li { margin: 7px 0; }
#extra { margin-top: 16px; border: none; border-top: 1px solid #d4d4d4; padding-top: 12px; }
""",
)

DECK = genanki.Deck(DECK_ID, DECK_NAME)

# (Front, Back, [tags])
CARDS = [
    # ===================== Sinusitis =====================
    ('<b>Sinusitis — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li><b>¿Cuántos días lleva con síntomas?</b> → <10 días sugiere viral; >10 días o persistencia orienta a bacteriana.</li><li><b>¿Mejoró y volvió a empeorar (doble empeoramiento)?</b> → patrón bifásico orienta a sobreinfección bacteriana.</li><li>¿Tiene rinorrea purulenta, dolor/presión facial y obstrucción nasal? → tríada típica de rinosinusitis; la purulencia unilateral con dolor maxilar apoya bacteriana.</li><li>¿Fiebre alta, dolor intenso o cefalea? → fiebre >39 °C con dolor facial intenso refuerza sospecha bacteriana.</li><li><b>¿Dolor o edema periorbitario, alteración visual, diplopía o focalidad neurológica?</b> → banderas rojas de complicación (celulitis orbitaria / compromiso neurológico).</li><li>¿Episodios recurrentes, alergia, asma, pólipos o tabaquismo? → factores de cronicidad/recurrencia.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Realizo rinoscopia anterior elevando la punta nasal para ver la mucosa y el meato medio, busco rinorrea purulenta y edema. Hago percusión/palpación de senos frontales y maxilares evaluando dolor. Inspecciono región periorbitaria y motilidad ocular. Completo con otoscopia, exploro orofaringe con abatelenguas y palpo cuello en busca de adenopatías.»<ul><li>Rinoscopia: mucosa edematosa/eritematosa con secreción purulenta en meato medio → orienta a sinusitis.</li><li>Dolor a la palpación/percusión de senos maxilares o frontales.</li><li>Goteo retronasal purulento en orofaringe.</li><li><b>Edema/eritema periorbitario, proptosis, dolor a la motilidad ocular o limitación de la mirada → celulitis orbitaria (complicación).</b></li><li>Adenopatías cervicales; otoscopia para descartar otitis concomitante.</li></ul>',
     ['Simulacion2::Familiar-ORL::Sinusitis', 'Abordaje']),

    ('<b>Sinusitis — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Dx:</b> Rinosinusitis. <b>Viral (<10 días):</b> NO antibiótico → lavados nasales con solución salina, analgésicos (<b>paracetamol o ibuprofeno</b>), hidratación, vigilancia y consejería («no requiere antibiótico»).<br><b>Bacteriana (>10 días o doble empeoramiento):</b> <b>amoxicilina/ácido clavulánico 875/125 mg VO c/12 h por 5–7 días</b> (adultos) + lavados nasales + analgésicos.<br><b>Referencia:</b> celulitis orbitaria, alteración visual, compromiso neurológico o sin mejoría.<br><i>ECOE:</i> «Sinusitis bacteriana; inicio amoxicilina/clavulanato y medidas de soporte.»',
     ['Simulacion2::Familiar-ORL::Sinusitis', 'Manejo']),

    ('<b>SINUSITIS — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 28 años con 4 días de rinorrea, congestión nasal y presión facial leve, sin fiebre alta, en buen estado general. → NO antibiótico → <b>lavados nasales con solución salina</b>, analgésicos (<b>paracetamol o ibuprofeno</b>), hidratación y vigilancia. Consejería: «no requiere antibiótico», reconsultar si empeora o persiste >10 días.</li><li><b>Moderado:</b> Hombre de 40 años con 12 días de rinorrea purulenta y dolor maxilar; mejoró al día 6 y volvió a empeorar con fiebre. → <b>amoxicilina/ácido clavulánico 875/125 mg VO c/12 h por 5–7 días</b> + lavados nasales + analgésicos. Reconsultar si aparecen banderas rojas.</li><li><b>Difícil:</b> Adolescente de 16 años con sinusitis de 8 días que desarrolla edema y eritema periorbitario, dolor a la motilidad ocular y visión borrosa. → <b>Referencia urgente</b> a segundo nivel/urgencias por compromiso orbitario y visual. No demorar el manejo en domicilio.</li></ul>',
     ['Simulacion2::Familiar-ORL::Sinusitis', 'Caso']),

    # ===================== Sinusitis + Otitis + Neumonía (coinfección) =====================
    ('<b>Sinusitis + Otitis + Neumonía (coinfección) — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li>¿<b>Tiempo de evolución</b> y si hubo mejoría seguida de empeoramiento (curso bifásico)? → patrón viral que se sobreinfecta bacterianamente; >10 días orienta a sinusitis bacteriana.</li><li>¿<b>Fiebre alta, dolor facial/dental, rinorrea purulenta, otalgia</b> y dónde predomina el síntoma? → localiza el foco dominante (senos, oído medio, pulmón).</li><li>¿<b>Tos productiva, dolor torácico pleurítico, disnea</b>? → identifica afectación pulmonar (neumonía) como foco más grave a priorizar.</li><li>¿<b>Dificultad para respirar en reposo, sensación de fatiga o confusión</b>? → banderas rojas de gravedad/sepsis que cambian la conducta a referir.</li><li>¿<b>Comorbilidades</b> (EPOC, asma, diabetes, inmunosupresión), edad y embarazo? → riesgo de complicación y elección/ajuste de antibiótico.</li><li>¿<b>Alergia a betalactámicos</b> y antibióticos recientes? → seguridad del esquema y resistencia probable.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Tomo <b>signos vitales con saturación de O2</b>, valoro estado general y frecuencia respiratoria. Hago <b>rinoscopia anterior</b> buscando mucosa congestiva y secreción purulenta, y <b>palpo/percuto senos frontales y maxilares</b> buscando dolor. Realizo <b>otoscopia bilateral</b> evaluando la membrana timpánica. Inspecciono <b>orofaringe</b>, palpo <b>cuello en busca de adenopatías</b> y exploro tiroides con la deglución. Finalmente <b>ausculto tórax</b> en todos los campos.»<ul><li>SatO2, FR y estado general: definen si hay <b>gravedad</b>.</li><li>Dolor a la palpación de senos + rinorrea purulenta → <b>sinusitis bacteriana</b>.</li><li>Otoscopia: <b>tímpano abombado, eritematoso, opaco o con otorrea</b> → otitis media aguda.</li><li>Auscultación: <b>crepitantes, soplo tubárico, hipoventilación o matidez</b> → neumonía (foco más grave a priorizar).</li><li>Adenopatías cervicales reactivas; orofaringe sin causa alternativa.</li></ul>',
     ['Simulacion2::Familiar-ORL::Coinfeccion', 'Abordaje']),

    ('<b>Sinusitis + Otitis + Neumonía (coinfección) — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Dx:</b> coinfección de vía respiratoria (sinusitis + otitis media + neumonía). Lo clave es <b>priorizar el foco más grave y elegir el antibiótico que cubra la neumonía</b>.<br><b>Tratamiento:</b><ul><li>Si todo parece bacteriano y el paciente está estable → <b>amoxicilina/clavulanato 875/125 mg VO c/12 h</b> (cubre todos los focos).</li><li>Si la neumonía es el problema principal → <b>amoxicilina 1 g VO c/8 h</b> (o según guía local).</li></ul><b>Referir / hospitalizar si:</b> <b>saturación baja, disnea importante, sepsis o hipotensión</b>.<br>Consejería: hidratación, control de fiebre, signos de alarma respiratoria y reconsulta si empeora.',
     ['Simulacion2::Familiar-ORL::Coinfeccion', 'Manejo']),

    ('<b>SINUSITIS + OTITIS + NEUMONÍA (COINFECCIÓN) — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 32 años, 8 días de evolución con rinorrea purulenta, dolor en senos maxilares, otalgia derecha y tos. Afebril al momento, SatO2 97%, sin disnea; tímpano derecho abombado, dolor a palpación de senos, crepitantes basales escasos. → manejo ambulatorio con <b>amoxicilina/clavulanato 875/125 mg VO c/12 h</b> (cubre todos los focos). Sintomáticos, hidratación y signos de alarma.</li><li><b>Moderado:</b> Hombre de 45 años con tos productiva, dolor torácico pleurítico y fiebre de 5 días; refiere antecedente reciente de sinusitis. SatO2 95%, sin disnea de reposo, hemodinámicamente estable; a la auscultación crepitantes y soplo tubárico en base derecha. → tratar el foco más grave con <b>amoxicilina 1 g VO c/8 h</b> (o según guía local), que cubre el cuadro respiratorio. Manejo ambulatorio con vigilancia y reconsulta si aparecen datos de gravedad.</li><li><b>Difícil:</b> Adulto de 68 años con neumonía sobre cuadro de sinusitis/otitis previo, ahora con disnea importante en reposo, SatO2 88%, TA 85/50 y aspecto séptico. → NO manejo ambulatorio. <b>Referir / hospitalizar de inmediato</b> por saturación baja, disnea importante, sepsis e hipotensión. Estabilizar (oxígeno, accesos, líquidos) durante el traslado.</li></ul>',
     ['Simulacion2::Familiar-ORL::Coinfeccion', 'Caso']),

    # ===================== Otitis media aguda =====================
    ('<b>Otitis media aguda — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li><b>Otalgia</b>: inicio, intensidad, unilateral/bilateral → dolor agudo intenso orienta a OMA; pulsátil sugiere supuración a tensión.</li><li><b>Otorrea</b>: aparición y características → otorrea purulenta súbita con alivio del dolor sugiere <b>perforación timpánica</b>.</li><li><b>Fiebre y síntomas catarrales previos</b> (rinorrea, tos, congestión) → IVRS reciente es el antecedente típico que precede a la OMA.</li><li><b>Hipoacusia y sensación de oído ocupado</b> → orienta a ocupación del oído medio por exudado.</li><li><b>Banderas rojas</b>: dolor/eritema retroauricular, desplazamiento del pabellón, parálisis facial, cefalea intensa, vómito, alteración del estado de alerta → sospecha de <b>mastoiditis, parálisis facial o complicación intracraneal</b>.</li><li><b>Antecedentes</b>: episodios previos, inmunodepresión, alergias a fármacos → orientan recurrencia y elección/seguridad del tratamiento.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Realizo otoscopia traccionando el pabellón hacia arriba y atrás para rectificar el CAE; inspecciono el conducto y la membrana timpánica valorando color, abombamiento, movilidad y presencia de otorrea. Completo con rinoscopia anterior, exploración de orofaringe y palpación cervical buscando adenopatías, además de inspección y palpación de la región mastoidea (retroauricular).» <ul><li><b>Membrana timpánica abombada, hiperémica y opaca</b>, con pérdida del triángulo luminoso → confirma OMA.</li><li>Disminución de la movilidad timpánica (otoscopia neumática) y/o nivel hidroaéreo → exudado en oído medio.</li><li>Otorrea purulenta en CAE con <b>perforación</b> visible → OMA supurada.</li><li>Rinoscopia/orofaringe: congestión, rinorrea → confirma IVRS asociada.</li><li><b>Eritema, dolor y abombamiento retroauricular con desplazamiento del pabellón</b> → mastoiditis (bandera roja).</li><li>Asimetría facial / parálisis facial periférica → complicación neurológica.</li></ul>',
     ['Simulacion2::Familiar-ORL::OtitisMediaAguda', 'Abordaje']),

    ('<b>Otitis media aguda — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Diagnóstico</b>: clínico, por otalgia + IVRS previa y otoscopia con membrana timpánica abombada e hiperémica.<br><b>Tratamiento (adulto)</b>: <b>amoxicilina 500 mg c/8 h</b> o <b>875 mg c/12 h durante 5–7 días</b> + analgésicos (<b>paracetamol</b>, <b>ibuprofeno</b>).<br><b>Criterios de referencia</b>: <b>mastoiditis, parálisis facial, persistencia y complicaciones intracraneales</b>.<br>Consejería: control del dolor, completar el antibiótico y reconsulta si aparecen banderas rojas.<br><i>ECOE:</i> «Otitis media aguda; indico amoxicilina y analgesia.»',
     ['Simulacion2::Familiar-ORL::OtitisMediaAguda', 'Manejo']),

    ('<b>OTITIS MEDIA AGUDA — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 28 años con otalgia derecha leve de 24 h tras un cuadro catarral; afebril, otoscopia con leve hiperemia timpánica sin abombamiento marcado y buen estado general. → : <b>analgesia</b> (paracetamol o ibuprofeno) con <b>observación</b>; sin antibiótico de inicio. Reconsulta si empeora o no mejora en 48–72 h.</li><li><b>Moderado:</b> Hombre de 35 años con otalgia intensa de 2 días, fiebre 38.5 °C e hipoacusia; otoscopia con membrana timpánica abombada e hiperémica. → : <b>amoxicilina 500 mg c/8 h</b> o <b>875 mg c/12 h por 5–7 días</b> + analgésicos (<b>paracetamol</b>, <b>ibuprofeno</b>).</li><li><b>Difícil:</b> Mujer de 40 años con OMA de varios días que presenta dolor, eritema y abombamiento retroauricular con desplazamiento del pabellón y fiebre alta. → : <b>referir</b> de inmediato. Son criterios de referencia: <b>mastoiditis, parálisis facial y complicaciones intracraneales</b>.</li></ul>',
     ['Simulacion2::Familiar-ORL::OtitisMediaAguda', 'Caso']),

    # ===================== Otitis media serosa =====================
    ('<b>Otitis media serosa — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li><b>¿Sensación de oído tapado o hipoacusia?</b> → síntoma cardinal de derrame; en niños sospechar si sube el volumen, pide repetir o baja rendimiento escolar.</li><li><b>¿Otalgia o fiebre?</b> → su ausencia diferencia de otitis media aguda; dolor leve/presión es típico de OME.</li><li><b>¿Cuadro catarral, rinitis o alergia recientes?</b> → disfunción tubárica por inflamación; orienta a rinitis asociada como factor desencadenante.</li><li><b>¿Cuánto lleva con los síntomas?</b> → distingue OME reciente de persistente (>3 meses), clave para la decisión de referir.</li><li><b>¿Ronquido, respiración bucal o infecciones de repetición?</b> → sospecha de hipertrofia adenoidea como causa de obstrucción tubárica.</li><li><b>¿Episodios previos de otitis o factores de riesgo?</b> → guardería, tabaquismo pasivo, paladar hendido; orientan a recurrencia y pronóstico.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Realizo otoscopia traccionando el pabellón hacia arriba y atrás; observo color, posición y movilidad de la membrana timpánica y busco nivel hidroaéreo o burbujas. Hago rinoscopia anterior para valorar mucosa y secreción nasal, exploro la orofaringe y, en niños, valoro signos de obstrucción adenoidea. Completo con palpación cervical en busca de adenopatías.»<ul><li><b>Membrana timpánica deslustrada/ámbar o azulada</b>, retraída o abombada → derrame en oído medio.</li><li><b>Nivel hidroaéreo o burbujas</b> retrotimpánicas → signo confirmatorio de OME.</li><li><b>Movilidad timpánica disminuida</b> (otoscopia neumática) → derrame; sin neumática, ausencia de reflejo luminoso normal.</li><li><b>Sin abombamiento purulento ni signos inflamatorios agudos</b> → descarta otitis media aguda.</li><li>Mucosa nasal congestiva/rinorrea → rinitis asociada; cuello sin adenopatías significativas.</li></ul>',
     ['Simulacion2::Familiar-ORL::OtitisMediaSerosa', 'Abordaje']),

    ('<b>Otitis media serosa — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Diagnóstico:</b> otitis media serosa (derrame en oído medio sin signos de infección aguda), confirmado por otoscopia.<br><b>Tratamiento:</b> <b>NO antibiótico</b>. <b>Observación</b>. Pueden usarse <b>lavados nasales y corticoide nasal si hay rinitis asociada</b>.<br><b>Seguimiento:</b> reevaluar en <b>4–12 semanas</b>.<br><b>Referencia a ORL:</b> <b>persistencia prolongada</b> o <b>hipoacusia importante</b>.<br><i>Consejería:</i> explicar que suele resolver sola, evitar exposición a humo de tabaco y tratar la causa nasal/alérgica.',
     ['Simulacion2::Familiar-ORL::OtitisMediaSerosa', 'Manejo']),

    ('<b>OTITIS MEDIA SEROSA — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Niño de 5 años, asintomático, traído por revisión tras un catarro hace 2 semanas. Otoscopia: tímpano ámbar con nivel hidroaéreo, sin otalgia ni fiebre. → <b>observación</b> sin antibiótico. <b>Seguimiento en 4–12 semanas</b>; tranquilizar a la familia indicando que tiende a la resolución espontánea.</li><li><b>Moderado:</b> Mujer de 28 años con sensación de oído tapado y rinitis alérgica activa con congestión nasal. Otoscopia: tímpano retraído deslustrado con derrame, sin signos de infección aguda. → sin antibiótico. <b>Corticoide nasal + lavados nasales</b> para tratar la rinitis. <b>Seguimiento en 4–12 semanas</b> y reevaluar resolución del derrame.</li><li><b>Difícil:</b> Niño de 6 años con derrame bilateral persistente >3 meses; los padres y la maestra notan que no responde al llamado y ha bajado el rendimiento escolar. → <b>referir a ORL</b> por persistencia prolongada e hipoacusia significativa (valoración audiológica y posible miringotomía/tubos). Continuar manejo de causa nasal mientras tanto.</li></ul>',
     ['Simulacion2::Familiar-ORL::OtitisMediaSerosa', 'Caso']),

    # ===================== Perforación timpánica =====================
    ('<b>Perforación timpánica — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li><b>Mecanismo:</b> ¿barotrauma (buceo/vuelo/bofetada), trauma con hisopo/objeto, o tras otitis media? → orienta etiología y tamaño/localización del defecto</li><li><b>Otorrea:</b> ¿supuración? ¿purulenta, fétida o sanguinolenta? → infección activa (ciprofloxacino) vs otorragia traumática</li><li><b>Tiempo de evolución:</b> ¿cuántos días/semanas/meses? → bandera roja si <b>>2 meses</b> (no cierre espontáneo)</li><li><b>Audición y acúfeno:</b> ¿hipoacusia, sensación de oído tapado, zumbido? → cuantificar <b>hipoacusia significativa</b> (criterio de referencia)</li><li><b>Vértigo/desequilibrio:</b> ¿giro de objetos, náusea? → sospecha de afectación de oído interno/fístula</li><li><b>Antecedentes y exposición:</b> ¿otitis de repetición, cirugía ótica previa, natación o entrada de agua? → riesgo de reinfección y plan de cuidados (oído seco)</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Realizo otoscopia traccionando el pabellón hacia arriba y atrás para rectificar el conducto; inspecciono primero el oído sano y luego el afectado. Valoro conducto auditivo externo (cerumen, secreción, edema), identifico la membrana timpánica, describo la perforación —localización por cuadrantes, tamaño relativo y bordes—, y observo si hay otorrea o pólipos. Complemento con acumetría: Weber y Rinne para caracterizar la hipoacusia.»<ul><li><b>Perforación visible</b> de la membrana: defecto central/marginal, tamaño pequeño vs grande</li><li><b>Otorrea purulenta</b> en el conducto → infección activa</li><li><b>Rinne y Weber:</b> patrón de <b>hipoacusia conductiva</b> (Weber lateraliza al oído afectado, Rinne negativo)</li><li>Bordes engrosados/cronicidad y ausencia de cicatrización → orienta a persistencia</li><li>Signos de alarma: vértigo, nistagmo o parálisis facial → sospecha de afectación más allá del oído medio</li></ul>',
     ['Simulacion2::Familiar-ORL::PerforacionTimpanica', 'Abordaje']),

    ('<b>Perforación timpánica — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Dx:</b> perforación timpánica (otoscopia + hipoacusia conductiva en acumetría).<br><b>Medidas generales:</b> mantener el <b>oído seco</b>, <b>NO introducir hisopos</b>, <b>NO nadar</b>.<br><b>Si hay infección/otorrea:</b> <b>ciprofloxacino ótico</b>.<br><b>Referencia a ORL:</b> perforación grande, <b>persistencia >2 meses</b>, o <b>hipoacusia significativa</b>.',
     ['Simulacion2::Familiar-ORL::PerforacionTimpanica', 'Manejo']),

    ('<b>PERFORACIÓN TIMPÁNICA — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 22 años acude tras una bofetada en el oído ayer; refiere oído tapado leve y otalgia que ya cedió. Otoscopia: perforación pequeña central, sin secreción, conducto limpio. → manejo conservador y consejería — mantener el <b>oído seco</b>, <b>NO usar hisopos</b>, <b>NO nadar</b>. Vigilar cierre espontáneo y signos de infección.</li><li><b>Moderado:</b> Niño de 8 años con antecedente de otitis media; desde hace 3 días presenta otorrea purulenta y oído tapado. Otoscopia: perforación con <b>supuración activa</b> en el conducto. → <b>ciprofloxacino ótico</b>. Mantener <b>oído seco</b>, <b>NO hisopos</b>, <b>NO nadar</b>. Reevaluar y referir si no resuelve o aparecen criterios de alarma.</li><li><b>Difícil:</b> Hombre de 45 años con perforación timpánica de <b>4 meses</b> de evolución que no ha cerrado; describe hipoacusia marcada que interfiere con su trabajo. Otoscopia: perforación amplia. → <b>referir a ORL</b> (no cierre espontáneo; valoración para timpanoplastia). Mantener oído seco, no hisopos, no nadar mientras tanto.</li></ul>',
     ['Simulacion2::Familiar-ORL::PerforacionTimpanica', 'Caso']),

    # ===================== Otitis externa =====================
    ('<b>Otitis externa — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li>¿Dolor de oído que aumenta al traccionar el pabellón o presionar el trago? → muy sugestivo de <b>otitis externa</b> (vs. otitis media).</li><li>¿Antecedente de natación, baño frecuente o humedad en el oído? → factor de riesgo de <b>otitis externa difusa</b> (oído del nadador).</li><li>¿Uso de hisopos, audífonos, tapones o manipulación del conducto? → trauma/maceración de la piel del conducto.</li><li>¿Prurito, sensación de plenitud o supuración (otorrea)? → orienta a inflamación del conducto; otorrea fétida puede sugerir sobreinfección.</li><li>¿Hipoacusia o tinnitus? → edema/detritos obstruyendo el conducto.</li><li>¿<b>Diabetes, inmunosupresión</b>, dolor desproporcionado o que no cede? → bandera roja para <b>otitis externa maligna/necrosante</b>.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Inspecciono el pabellón auricular y la región retroauricular buscando eritema, edema o secreción; realizo la <b>maniobra de tracción del pabellón y presión sobre el trago</b> para reproducir el dolor; traiciono el conducto y realizo <b>otoscopia</b> evaluando el conducto auditivo externo y la membrana timpánica; palpo los <b>ganglios periauriculares y cervicales</b>.»<ul><li><b>Dolor a la tracción del pabellón/presión del trago</b> → signo clave de otitis externa.</li><li>Otoscopia: conducto <b>eritematoso, edematoso, con detritos o secreción</b>; membrana timpánica normal o difícil de visualizar.</li><li>Posible adenopatía periauricular o cervical sensible.</li><li>Buscar <b>tejido de granulación en el piso del conducto</b> → alarma de otitis externa maligna.</li></ul>',
     ['Simulacion2::Familiar-ORL::OtitisExterna', 'Abordaje']),

    ('<b>Otitis externa — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Dx:</b> otitis externa (clínico: dolor a la tracción del pabellón + conducto inflamado).<br><b>Tratamiento:</b><ul><li><b>Leve:</b> gotas acidificantes (<b>ácido acético 2%</b>).</li><li><b>Moderada:</b> <b>ciprofloxacino ótico</b>, o <b>ciprofloxacino + dexametasona</b>, por <b>7–10 días</b>.</li><li>Analgesia: <b>paracetamol</b> o <b>ibuprofeno</b>.</li></ul><b>Consejería:</b> mantener el oído seco, <b>no usar hisopos</b>.<br><b>Referencia:</b> paciente <b>diabético, inmunosuprimido o sospecha de otitis externa maligna</b>.<br><i>ECOE:</i> «Otitis externa; manejo con gotas óticas y mantener oído seco.»',
     ['Simulacion2::Familiar-ORL::OtitisExterna', 'Manejo']),

    ('<b>OTITIS EXTERNA — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 24 años, nadadora, con prurito y molestia leve en el oído derecho tras varios días en la piscina. A la exploración hay dolor leve a la tracción del pabellón y conducto algo eritematoso, sin secreción significativa. → <b>gotas acidificantes (ácido acético 2%)</b>. Consejería: <b>mantener el oído seco, no usar hisopos</b>. Analgesia con <b>paracetamol/ibuprofeno</b> si hay dolor.</li><li><b>Moderado:</b> Hombre de 38 años con dolor importante en el oído izquierdo, otorrea y conducto eritematoso, edematoso con detritos a la otoscopia. Dolor marcado a la presión del trago. → <b>ciprofloxacino ótico ± dexametasona</b> por <b>7–10 días</b> + analgesia (<b>paracetamol/ibuprofeno</b>). Consejería: <b>mantener oído seco, no usar hisopos</b>.</li><li><b>Difícil:</b> Hombre de 68 años <b>diabético</b> con dolor de oído intenso, persistente y desproporcionado, otorrea y tejido de granulación en el piso del conducto a la otoscopia. → <b>referir de forma urgente</b>. Referencia obligada en <b>diabético, inmunosuprimido o sospecha de otitis externa maligna</b>.</li></ul>',
     ['Simulacion2::Familiar-ORL::OtitisExterna', 'Caso']),

    # ===================== Faringitis estreptocócica =====================
    ('<b>Faringitis estreptocócica — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li><b>Dolor de garganta de inicio súbito</b> → orienta a etiología bacteriana (estreptococo) más que viral.</li><li><b>Fiebre alta (≥38 °C)</b> → criterio de Centor; apoya origen estreptocócico.</li><li><b>¿Tos, rinorrea, disfonía?</b> → su <i>ausencia</i> orienta a estreptococo; su presencia sugiere viral.</li><li><b>Edad</b> → mayor probabilidad estreptocócica entre 3–14 años.</li><li><b>Contactos enfermos / escuela</b> → orienta a transmisión y refuerza sospecha.</li><li><b>Odinofagia que impide tragar saliva, voz «de papa caliente», trismus</b> → bandera roja de complicación (absceso periamigdalino).</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Con buena iluminación y abatelenguas inspecciono la orofaringe valorando amígdalas, pilares y pared posterior; busco eritema, exudado y simetría. Palpo cadenas cervicales, en especial las adenopatías cervicales anteriores, evaluando tamaño y dolor. Tomo temperatura y descarto signos de obstrucción: trismus, desviación de úvula y dificultad respiratoria.»<ul><li><b>Eritema faríngeo con exudado amigdalino</b> → apoya estreptococo.</li><li><b>Adenopatías cervicales anteriores dolorosas</b> → criterio de Centor.</li><li><b>Fiebre ≥38 °C</b> → criterio de Centor.</li><li><b>Ausencia de tos</b> → criterio de Centor.</li><li><b>Úvula desviada, abombamiento periamigdalino, trismus o voz «de papa caliente»</b> → bandera roja de absceso periamigdalino.</li></ul>',
     ['Simulacion2::Familiar-ORL::Faringitis', 'Abordaje']),

    ('<b>Faringitis estreptocócica — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Diagnóstico:</b> faringitis estreptocócica (clínica ± criterios de Centor).<br><b>Tratamiento de primera línea:</b> <b>penicilina V</b> o <b>amoxicilina 500 mg c/12 h por 10 días</b>.<br>Si <b>alergia a penicilina: azitromicina</b>.<br><b>Consejería:</b> completar todo el tratamiento, evitar compartir utensilios.<br><b>Referencia:</b> <b>absceso periamigdalino, dificultad respiratoria o trismus</b>.<br><i>ECOE:</i> «Faringitis estreptocócica; amoxicilina 10 días para prevenir complicaciones.»',
     ['Simulacion2::Familiar-ORL::Faringitis', 'Manejo']),

    ('<b>FARINGITIS ESTREPTOCÓCICA — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Niño de 8 años con odinofagia de inicio súbito, fiebre 38.5 °C, sin tos ni rinorrea; amígdalas eritematosas con exudado y adenopatías cervicales anteriores dolorosas. → <b>amoxicilina 500 mg c/12 h por 10 días</b> (o penicilina V 10 días). Consejería: completar el tratamiento y no compartir utensilios.</li><li><b>Moderado:</b> Mujer de 22 años con cuadro típico de faringitis estreptocócica, pero refiere antecedente de urticaria y angioedema con penicilina. → <b>azitromicina</b> como alternativa. Misma consejería: completar el tratamiento y evitar compartir utensilios.</li><li><b>Difícil:</b> Varón de 19 años con odinofagia intensa unilateral, fiebre, voz «de papa caliente», trismus y abombamiento periamigdalino con dificultad para tragar saliva. → <b>referir de forma urgente</b> (dificultad respiratoria, trismus, absceso periamigdalino son criterios de referencia).</li></ul>',
     ['Simulacion2::Familiar-ORL::Faringitis', 'Caso']),

    # ===================== Rinitis alérgica =====================
    ('<b>Rinitis alérgica — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li>¿Tiene <b>estornudos en salva, rinorrea acuosa, prurito nasal/ocular y congestión</b>? → tétrada clásica de rinitis alérgica.</li><li>¿Los síntomas son <b>estacionales o perennes</b>, y mejoran al cambiar de ambiente? → estacional sugiere pólenes; perenne sugiere ácaros, epitelios o mohos.</li><li>¿Identifica <b>desencadenantes</b> (polvo, mascotas, polen, humo)? → orienta al alérgeno y al control ambiental.</li><li>¿Antecedente personal o familiar de <b>atopia, asma o dermatitis</b>? → apoya base alérgica y marcha atópica.</li><li>¿Síntomas <b>unilaterales, rinorrea purulenta/sanguinolenta, dolor facial o anosmia</b>? → bandera roja: descarta cuerpo extraño, sinusitis o pólipos/tumor.</li><li>¿Qué tratamientos previos usó y con qué respuesta? → orienta escalamiento terapéutico o necesidad de referencia.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Realizo inspección facial buscando saludo alérgico y ojeras; con espéculo nasal hago <b>rinoscopia anterior</b> observando mucosa, cornetes y secreción; reviso <b>orofaringe</b> con abatelenguas, hago <b>otoscopia</b> bilateral para descartar otitis media con derrame, y palpo cuello en busca de adenopatías.» <ul><li>Mucosa nasal <b>pálida/violácea y edematosa</b> con rinorrea acuosa clara → orienta a rinitis alérgica.</li><li>Cornetes inferiores hipertróficos que reducen la luz nasal.</li><li>Signos faciales: <b>surco nasal transverso</b>, ojeras alérgicas (Dennie-Morgan), respiración bucal.</li><li>Orofaringe con empedrado linfoide por goteo posterior; otoscopia normal o con derrame.</li><li><b>Alerta</b>: masa gris/perlada (pólipos), mucosa eritematosa con pus o desviación marcada → no es cuadro alérgico simple.</li></ul>',
     ['Simulacion2::Familiar-ORL::RinitisAlergica', 'Abordaje']),

    ('<b>Rinitis alérgica — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Dx:</b> rinitis alérgica, clínico (tétrada + atopia, sin datos de alarma).<br><b>Medidas generales:</b> evitar alérgeno y <b>lavados nasales</b>.<br><b>Antihistamínicos:</b> <b>loratadina 10 mg/día</b> o <b>cetirizina 10 mg/día</b>.<br><b>Corticoides nasales:</b> <b>fluticasona 1–2 disparos por fosa/día</b> o <b>mometasona 2 disparos por fosa/día</b>.<br><b>Referencia:</b> <b>mala respuesta</b>, <b>sospecha de pólipos</b> o <b>diagnóstico incierto</b>.<br><i>ECOE:</i> «Rinitis alérgica; antihistamínico, corticoide nasal y control ambiental.»',
     ['Simulacion2::Familiar-ORL::RinitisAlergica', 'Manejo']),

    ('<b>RINITIS ALÉRGICA — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 22 años con estornudos, rinorrea acuosa y prurito nasal ocasionales en primavera, sin afectar sueño ni actividades. → <b>antihistamínico</b> (<b>loratadina 10 mg/día</b> o <b>cetirizina 10 mg/día</b>) + <b>control ambiental</b> (evitar alérgeno) + <b>lavados nasales</b>.</li><li><b>Moderado:</b> Hombre de 35 años con congestión nasal y rinorrea persistentes la mayoría de los días, que alteran su sueño; ya usa antihistamínico con respuesta parcial. → mantener antihistamínico y control ambiental, y <b>agregar corticoide nasal</b>: <b>fluticasona 1–2 disparos por fosa/día</b> o <b>mometasona 2 disparos por fosa/día</b>.</li><li><b>Difícil:</b> Mujer de 48 años con congestión nasal persistente, anosmia y obstrucción que no cede pese a antihistamínico y corticoide nasal bien usados; a la rinoscopia se observan masas grises perladas. → <b>referir</b> (mala respuesta / sospecha de pólipos / diagnóstico incierto) a ORL para valoración.</li></ul>',
     ['Simulacion2::Familiar-ORL::RinitisAlergica', 'Caso']),

    # ===================== Rinitis irritativa =====================
    ('<b>Rinitis irritativa — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li>¿Hay <b>exposición a un irritante</b> (humo de tabaco, polvo, productos de limpieza, vapores, contaminación laboral)? → relación temporal síntoma–exposición orienta a etiología irritativa.</li><li>¿Los síntomas <b>aparecen al exponerse y ceden al retirarse</b> del ambiente? → patrón irritativo (no alérgico ni infeccioso).</li><li>¿Predomina <b>obstrucción/rinorrea acuosa y prurito o estornudos</b>? → poco prurito/estornudos aleja de alérgica; descarga clara aleja de infecciosa.</li><li>¿Hay <b>estacionalidad, atopia, asma o eccema</b> personal o familiar? → orienta a rinitis alérgica como diagnóstico alternativo.</li><li>¿Fiebre, secreción purulenta, dolor facial o síntomas >10 días? → <b>banderas de otra etiología</b> (infecciosa/rinosinusitis) que justifican estudiar.</li><li>¿Uso de descongestivos tópicos prolongados o fármacos (IECA, etc.)? → descarta rinitis medicamentosa.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Realizo <b>rinoscopia anterior</b> con espéculo y buena iluminación para inspeccionar mucosa, cornetes y secreciones; exploro la <b>orofaringe</b> con abatelenguas buscando descarga posterior; hago <b>otoscopia bilateral</b> para descartar afección de oído medio; y <b>palpo el cuello y la tiroides con la deglución</b>, además de cadenas ganglionares cervicales en busca de adenopatías.»<ul><li><b>Mucosa eritematosa/edematosa</b> con rinorrea acuosa o seromucosa, sin palidez típica de la alérgica.</li><li>Cornetes congestivos sin pólipos.</li><li><b>Ausencia de secreción purulenta</b> y de descarga posterior abundante (aleja de infecciosa/sinusitis).</li><li>Otoscopia normal; orofaringe sin exudado.</li><li><b>Sin adenopatías significativas</b> ni alteración tiroidea a la palpación.</li></ul>',
     ['Simulacion2::Familiar-ORL::RinitisIrritativa', 'Abordaje']),

    ('<b>Rinitis irritativa — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Dx:</b> rinitis irritativa (síntomas nasales por exposición a irritante, sin datos de etiología alérgica o infecciosa).<br><b>Tratamiento:</b> <b>eliminar/evitar el irritante</b> y realizar <b>lavados nasales</b>. Generalmente <b>NO requiere antihistamínicos</b>.<br><b>Referencia:</b> <b>persistencia de los síntomas</b> o <b>sospecha de otra etiología</b>.',
     ['Simulacion2::Familiar-ORL::RinitisIrritativa', 'Manejo']),

    ('<b>RINITIS IRRITATIVA — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 32 años con rinorrea acuosa y congestión que aparecen al limpiar la casa con cloro y amoniaco; ceden al salir al aire libre. Sin fiebre ni prurito. → <b>eliminar el irritante</b> (ventilar, usar productos sin amoniaco/cloro, mascarilla) + <b>lavados nasales</b>. No requiere antihistamínico.</li><li><b>Moderado:</b> Hombre de 45 años, obrero, con congestión y rinorrea durante toda la jornada en una fábrica con polvo y vapores; mejora los fines de semana. → <b>reforzar la evitación</b> del irritante (protección respiratoria, mejorar ventilación laboral) + <b>lavados nasales</b>. <b>Sin antihistamínico de rutina.</b></li><li><b>Difícil:</b> Mujer de 50 años que tras evitar el irritante y hacer lavados nasales persiste con obstrucción nasal unilateral y rinorrea; ahora con descarga posterior. → <b>referir/estudiar</b> para descartar otra causa (alérgica, infecciosa, estructural).</li></ul>',
     ['Simulacion2::Familiar-ORL::RinitisIrritativa', 'Caso']),

    # ===================== Bocio =====================
    ('<b>Bocio — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li><b>Tiempo de evolución y velocidad de crecimiento</b> → crecimiento rápido orienta a malignidad/sangrado y obliga a referencia.</li><li>Síntomas <b>compresivos</b>: disfagia, disnea, estridor, sensación de ahogo al acostarse → compresión traqueal/esofágica (bandera roja).</li><li>Síntomas de <b>hipertiroidismo</b>: palpitaciones, temblor, pérdida de peso, intolerancia al calor, insomnio → disfunción hiperfuncionante.</li><li>Síntomas de <b>hipotiroidismo</b>: fatiga, aumento de peso, intolerancia al frío, estreñimiento, somnolencia → disfunción hipofuncionante.</li><li>Disfonía/cambio de voz → afectación del nervio laríngeo recurrente (sospecha de malignidad).</li><li>Antecedentes: irradiación cervical, ingesta de yodo/déficit, fármacos (amiodarona, litio), historia familiar de tiroidopatía o cáncer → etiología y riesgo.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Inspecciono el cuello con el paciente sentado, buscando asimetría o masa en región anterior; pido que <b>degluta un sorbo de agua</b> para ver el ascenso de la glándula. Palpo la tiroides desde atrás con ambas manos, evaluando tamaño, consistencia, nódulos, movilidad con la deglución y dolor; ausculto por soplo. Palpo cadenas <b>ganglionares cervicales</b> y valoro signos compresivos (estridor, ingurgitación yugular, maniobra de Pemberton).» <ul><li><b>Difuso, blando, móvil con deglución</b> → bocio simple/eutiroideo.</li><li>Nódulo <b>duro, fijo, irregular</b> o adenopatías → sospecha de malignidad.</li><li><b>Soplo tiroideo</b> + temblor/taquicardia → hipertiroidismo.</li><li><b>Estridor, Pemberton positivo, ingurgitación</b> → compresión (referencia inmediata).</li></ul>',
     ['Simulacion2::Familiar-ORL::Bocio', 'Abordaje']),

    ('<b>Bocio — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Dx:</b> bocio; clasificar según función tiroidea con perfil tiroideo y USG.<br><b>Tratamiento:</b><ul><li>Función tiroidea <b>normal (eutiroideo)</b> → <b>observación + USG tiroideo</b>.</li><li><b>Hipotiroidismo</b> → <b>levotiroxina ~1.6 mcg/kg/día</b>.</li><li><b>Hipertiroidismo</b> → <b>referir a Endocrinología</b>.</li></ul><b>Referencia inmediata:</b> compresión traqueal, disfagia progresiva o crecimiento rápido.<br><i>ECOE:</i> «Solicito perfil tiroideo y ultrasonido para definir etiología.»',
     ['Simulacion2::Familiar-ORL::Bocio', 'Manejo']),

    ('<b>BOCIO — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 38 años con aumento difuso del cuello de meses de evolución, sin síntomas; perfil tiroideo normal. → <b>observación + USG tiroideo</b> para caracterizar la glándula; seguimiento clínico.</li><li><b>Moderado:</b> Mujer de 45 años con bocio, fatiga, aumento de peso e intolerancia al frío; TSH elevada con T4 baja. → <b>levotiroxina ~1.6 mcg/kg/día</b> y control. (Si fuera hipertiroidismo → <b>referir a Endocrinología</b>.)</li><li><b>Difícil:</b> Hombre de 60 años con bocio que ha crecido rápidamente en semanas, refiere disfagia progresiva y sensación de ahogo al acostarse. → <b>referencia inmediata</b> para valoración (vía aérea/cirugía).</li></ul>',
     ['Simulacion2::Familiar-ORL::Bocio', 'Caso']),

    # ===================== Nódulo tiroideo =====================
    ('<b>Nódulo tiroideo — Abordaje:</b> ¿qué pregunto, cómo exploro y qué verbalizo?',
     '<b>Interrogatorio.</b> <ul><li><b>¿Hace cuánto lo nota y ha crecido rápido?</b> → crecimiento rápido = dato de alarma (sospecha malignidad).</li><li><b>¿Dolor, disfonía o disfagia?</b> → disfonía orienta a invasión del recurrente / alarma.</li><li><b>¿Síntomas de hiper- (palpitaciones, temblor, pérdida de peso, calor) o hipotiroidismo (fatiga, frío, estreñimiento)?</b> → orienta función y necesidad de gammagrafía si hay hipertiroidismo.</li><li><b>¿Antecedente de radiación a cuello/cabeza en la infancia?</b> → factor de riesgo de malignidad.</li><li><b>¿Historia familiar de cáncer tiroideo o MEN?</b> → riesgo de carcinoma medular/familiar.</li><li><b>¿Adenopatías o masas cervicales asociadas?</b> → ganglios = dato de alarma.</li></ul><br><b>Exploración.</b> <i>Verbalizo:</i> «Me coloco por detrás del paciente, con el cuello en ligera extensión. Localizo el cartílago tiroides y palpo ambos lóbulos tiroideos con los pulpejos; pido al paciente que <b>degluta</b> un sorbo de agua para confirmar que la masa asciende con la deglución, lo que indica origen tiroideo. Caracterizo el nódulo (tamaño, consistencia, movilidad, bordes) y exploro las cadenas ganglionares cervicales.»<br><ul><li><b>Asciende con la deglución</b> → confirma origen tiroideo.</li><li>Nódulo blando, liso, móvil → orienta a benignidad.</li><li><b>Duro, irregular, fijo a planos profundos</b> → dato de alarma.</li><li><b>Adenopatías cervicales palpables</b> → dato de alarma.</li><li>Signos asociados: <b>disfonía</b>, soplo tiroideo, signos de disfunción tiroidea.</li></ul>',
     ['Simulacion2::Familiar-ORL::NoduloTiroideo', 'Abordaje']),

    ('<b>Nódulo tiroideo — Manejo:</b> Dx + tratamiento + referencia/consejería',
     '<b>Estudio de elección: USG tiroideo</b> (NO gammagrafía de entrada), junto con <b>TSH</b>.<br><ul><li>Si <b>TSH baja</b> → <b>gammagrafía</b> (nódulo caliente vs frío).</li><li>Si nódulo <b>sospechoso</b> → <b>BAAF</b> (biopsia por aspiración con aguja fina).</li></ul><b>Datos de alarma:</b> duro, irregular, fijo, adenopatías, disfonía, crecimiento rápido.<br><b>Referencia:</b> Endocrinología o Cirugía de cabeza y cuello.<br><i>ECOE:</i> «Nódulo tiroideo; solicito TSH y ultrasonido, valorando BAAF si hay datos de alarma.»',
     ['Simulacion2::Familiar-ORL::NoduloTiroideo', 'Manejo']),

    ('<b>NÓDULO TIROIDEO — Caso escalonado.</b> ¿Conducta en leve → moderado → difícil?',
     '<ul><li><b>Leve:</b> Mujer de 38 años, en quien se palpa incidentalmente un nódulo tiroideo pequeño, blando y móvil; sin síntomas, TSH normal y sin datos de alarma. → Nódulo tiroideo pequeño, eutiroideo y sin datos de alarma.<br>Conducta: <b>USG tiroideo + seguimiento</b>.</li><li><b>Moderado:</b> Mujer de 45 años con nódulo tiroideo y síntomas leves de hipertiroidismo; la <b>TSH está baja</b>. → Nódulo tiroideo con TSH baja (sospecha de nódulo hiperfuncionante).<br>Conducta: <b>gammagrafía</b> → si <b>nódulo caliente</b>, suele ser benigno.</li><li><b>Difícil:</b> Varón de 60 años con nódulo tiroideo <b>duro, fijo</b>, de <b>crecimiento rápido</b>, con <b>disfonía</b> y <b>adenopatías</b> cervicales. → Nódulo tiroideo con <b>datos de alarma</b> (duro/fijo, crecimiento rápido, disfonía, adenopatías) → sospecha de malignidad.<br>Conducta: <b>BAAF</b> + <b>referir a Endocrinología o Cirugía de cabeza y cuello</b>.</li></ul>',
     ['Simulacion2::Familiar-ORL::NoduloTiroideo', 'Caso']),

]


def main():
    for front, back, tags in CARDS:
        DECK.add_note(genanki.Note(model=MODEL, fields=[front, back], tags=tags))
    genanki.Package(DECK).write_to_file("simulacion-2-familiar-orl.apkg")
    with open("simulacion-2-familiar-orl.tsv", "w", encoding="utf-8") as f:
        for front, back, tags in CARDS:
            f.write(f"{front}\t{back}\t{' '.join(tags)}\n")
    print(f"Listo: {len(CARDS)} tarjetas -> simulacion-2-familiar-orl.apkg + .tsv")


if __name__ == "__main__":
    main()
